### ISSUE TITLE
Metadata option ignores provided takeout directory

### ISSUE THREAD

**Issue by geeksareforlife** [cbeley/GoogleTakeoutLocationHistoryParser#4]
Hi

Love this, it pretty much does exactly what I need!  I'd really like to get out the duration data, but when I use this command:

```
googleTakeoutLocationHistoryParser -k -m placeId durationInMS activityType  /home/james/temp/google-location/Takeout/
```

I get this error:

```
error: missing required argument 'googleTakeoutDirectory'
```

the script works perfectly without the `-m` option.  Even if I leave out the `-k` I get the same error

**Comment by cbeley** [comment]
Try

```
googleTakeoutLocationHistoryParser -k -m placeId durationInMS activityType -- /home/james/temp/google-location/Takeout/
```

`--` is commonly used to signify the end of a list of something in command arguments (See Guideline 10: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02). However, it is not technically anything special and not everyone follows it. But this tool does, and so does yargs, which is what I use for argument processing.

I should add a quick example of this to the readme though.

**Comment by geeksareforlife** [comment]
Works perfectly, thank you!

**Comment by cbeley** [comment]
0.1.1 has been published with the updated documentation; however, other than `--help` giving updated output, nothing else has changed.

Have fun!
